version: '2'
networks:
  geniebook-net:
    name: geniebook-net
services:
  consul:
    container_name: gb-consul
    image: bitnami/consul
    networks:
      - geniebook-net
    volumes:
      - ./data:/bitnami
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'


